name: HeroChat
version: 4.11.0
author: DThielke
main: com.herocraftonline.dthielke.herochat.HeroChat
description: Provides highly customizable chat channels
commands:
  ch:
    description: Lists all HeroChat commands 
    usage: Wrong usage. For help, type /<command> help
  qm:
    description: Sends a quick message to a channel without changing your focus
    usage: /<command> channel message
  leave:
    description: Leaves a channel
    usage: /<command> channel
  join:
    description: Joins a channel
    usage: /<command> channel
  mute:
    description: Mutes a player for a single channel
    usage: /<command> channel player
  gmute:
    description: Globally mutes a player
    usage: /<command> player
  tell:
    alias: [msg]
    description: Starts or ends a private conversation
    usage: /<command> player
  ignore:
    description: Ignores a player
    usage: /<command> player
